---
k8s_brew_packages:
  - argocd
  - colima # Container runtimes on macOS/Linux with minimal setup
  - dive # tool for exploring each layer in a docker image
  - docker
  # - docker-machine # Replaced by Rancher Desktop
  - docker-slim
  - istioctl
  - lazydocker
  - vmware-tanzu/carvel/ytt # Carvel ytt (yaml templating tool)
  - vladimirvivien/oss-tools/ktop
  - kubectx
  # - kubectl # Replaced by Rancher Desktop
  # - helm # Replaced by Rancher Desktop
  - norwoodj/tap/helm-docs
  - k3d
  - k9s
  - kompose
  - krew
  - kustomize
  - stern
  - velero
k8s_brew_cask_packages:
  - openlens
  #- rancher # Rancher Desktop
